// GENERATED from Notion Terms/Crosswalk (d4e19169-595f-45d8-8f52-5626ac009f72) — do not edit by hand.
// The full classified crosswalk vocabulary: every term the atlas has triaged, with its
// disposition and taxonomy. Used to give Mira breadth of vocabulary during the first
// orientation — she recognizes far more terms than the 165+ canonical patterns alone.
export const CROSSWALK_TERMS = [
  {"term":"Achievement-bound worth","disposition":"Alias","taxonomy":"Alias or synonym","canonical":"Productivity-Bound Worth"},
  {"term":"Adversarial Framing","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Adversarial Framing"},
  {"term":"Advice giving without invitation","disposition":"Noncanonical Taxonomy Term","taxonomy":"Relational behavior","canonical":"Advice-Giving as Avoidance"},
  {"term":"Advice-Giving as Avoidance","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Advice-Giving as Avoidance"},
  {"term":"All-or-Nothing Thinking","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"All-or-Nothing Thinking"},
  {"term":"All-or-Nothing Thinking / Black-and-White Thinking","disposition":"Alias","taxonomy":"Alias or synonym","canonical":"All-or-Nothing Thinking"},
  {"term":"Ambiguity maintenance","disposition":"Alias","taxonomy":"Alias or synonym","canonical":"Strategic Ambiguity"},
  {"term":"Analysis paralysis","disposition":"Noncanonical Taxonomy Term","taxonomy":"Cognitive state or process","canonical":"Certainty Seeking"},
  {"term":"Anger as Armor","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Anger as Armor"},
  {"term":"Anticipatory Defeat","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Anticipatory Defeat"},
  {"term":"Appearance-bound worth","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Appearance-Bound Worth"},
  {"term":"Appeasement","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Appeasement"},
  {"term":"Approval Seeking","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Approval Seeking"},
  {"term":"Approval-seeking","disposition":"Duplicate","taxonomy":"Alias or synonym","canonical":"Approval Seeking"},
  {"term":"Authority rejection","disposition":"Noncanonical Taxonomy Term","taxonomy":"Manifestation of a pattern","canonical":"Contrarianism"},
  {"term":"Avoidance","disposition":"Noncanonical Taxonomy Term","taxonomy":"Umbrella category or conceptual family","canonical":""},
  {"term":"Avoidant Compliance","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Avoidant Compliance"},
  {"term":"Avoidant independence","disposition":"Alias","taxonomy":"Alias or synonym","canonical":"Hyper-Independence"},
  {"term":"Blame shifting","disposition":"Duplicate","taxonomy":"Alias or synonym","canonical":"Blame Shifting"},
  {"term":"Blame Shifting","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Blame Shifting"},
  {"term":"Borrowed conviction","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Borrowed Conviction"},
  {"term":"Boundary collapse","disposition":"Duplicate","taxonomy":"Alias or synonym","canonical":"Boundary Collapse"},
  {"term":"Boundary Collapse","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Boundary Collapse"},
  {"term":"Boundary hardening","disposition":"Alias","taxonomy":"Alias or synonym","canonical":"Boundary Rigidity"},
  {"term":"Boundary Rigidity","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Boundary Rigidity"},
  {"term":"Breadcrumbing","disposition":"Noncanonical Taxonomy Term","taxonomy":"Relational behavior","canonical":"Strategic Ambiguity"},
  {"term":"Busyness as avoidance","disposition":"Duplicate","taxonomy":"Alias or synonym","canonical":"Busyness as Avoidance"},
  {"term":"Busyness as Avoidance","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Busyness as Avoidance"},
  {"term":"Busyness as Identity","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Busyness as Identity"},
  {"term":"Care as identity","disposition":"Noncanonical Taxonomy Term","taxonomy":"Manifestation of a pattern","canonical":"Indispensability"},
  {"term":"Catastrophizing","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Catastrophizing"},
  {"term":"Certainty Seeking","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Certainty Seeking"},
  {"term":"Certainty through doctrine","disposition":"Noncanonical Taxonomy Term","taxonomy":"Manifestation of a pattern","canonical":"Borrowed Conviction"},
  {"term":"Chameleon identity","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Chameleon Identity"},
  {"term":"Charm as protection","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Charm as Protection"},
  {"term":"Checking rituals","disposition":"Noncanonical Taxonomy Term","taxonomy":"Manifestation of a pattern","canonical":"Compulsive Checking"},
  {"term":"Chronic Ambivalence","disposition":"Noncanonical Taxonomy Term","taxonomy":"Cognitive state or process","canonical":"Permanent Optionality"},
  {"term":"Chronic distraction","disposition":"Noncanonical Taxonomy Term","taxonomy":"Coping strategy","canonical":""},
  {"term":"Chronic Doubt","disposition":"Noncanonical Taxonomy Term","taxonomy":"Cognitive state or process","canonical":"Certainty Seeking"},
  {"term":"Clinging","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Clinging"},
  {"term":"Coercive Caretaking","disposition":"Noncanonical Taxonomy Term","taxonomy":"Safety-framework term","canonical":"Soliciting Dependence"},
  {"term":"Coercive Control","disposition":"Noncanonical Taxonomy Term","taxonomy":"Safety-framework term","canonical":""},
  {"term":"Commitment avoidance","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Commitment Avoidance"},
  {"term":"Comparison","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Comparison"},
  {"term":"Compartmentalization","disposition":"Alias","taxonomy":"Alias or synonym","canonical":"Compartmentalizing"},
  {"term":"Compartmentalizing","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Compartmentalizing"},
  {"term":"Compartmented persona","disposition":"Noncanonical Taxonomy Term","taxonomy":"Manifestation of a pattern","canonical":"Compartmentalizing"},
  {"term":"Competitive Invalidation","disposition":"Noncanonical Taxonomy Term","taxonomy":"Relational behavior","canonical":"Devaluation"},
  {"term":"Compulsive Achievement","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Compulsive Achievement"},
  {"term":"Compulsive apologizing","disposition":"Noncanonical Taxonomy Term","taxonomy":"Manifestation of a pattern","canonical":"People-Pleasing"},
  {"term":"Compulsive Caretaking","disposition":"Noncanonical Taxonomy Term","taxonomy":"Manifestation of a pattern","canonical":"Overfunctioning"},
  {"term":"Compulsive Checking","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Compulsive Checking"},
  {"term":"Compulsive Contact","disposition":"Noncanonical Taxonomy Term","taxonomy":"Manifestation of a pattern","canonical":"Clinging"},
  {"term":"Compulsive fixing","disposition":"Noncanonical Taxonomy Term","taxonomy":"Manifestation of a pattern","canonical":"Overfunctioning"},
  {"term":"Compulsive productivity","disposition":"Noncanonical Taxonomy Term","taxonomy":"Manifestation of a pattern","canonical":"Productivity-Bound Worth"},
  {"term":"Compulsive Rehearsal","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Compulsive Rehearsal"},
  {"term":"Compulsive scrolling","disposition":"Noncanonical Taxonomy Term","taxonomy":"Coping strategy","canonical":""},
  {"term":"Conditional Warmth","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Conditional Warmth"},
  {"term":"Confirmation seeking","disposition":"Duplicate","taxonomy":"Alias or synonym","canonical":"Reassurance Seeking"},
  {"term":"Confirmation Seeking","disposition":"Alias","taxonomy":"Alias or synonym","canonical":"Reassurance Seeking"},
  {"term":"Conflict avoidance","disposition":"Duplicate","taxonomy":"Alias or synonym","canonical":"Conflict Avoidance"},
  {"term":"Conflict Avoidance","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Conflict Avoidance"},
  {"term":"Conflict creation","disposition":"Noncanonical Taxonomy Term","taxonomy":"Relational behavior","canonical":"Adversarial Framing"},
  {"term":"Contempt","disposition":"Noncanonical Taxonomy Term","taxonomy":"Emotional state","canonical":"Devaluation"},
  {"term":"Contrarianism","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Contrarianism"},
  {"term":"Control-Seeking","disposition":"Noncanonical Taxonomy Term","taxonomy":"Umbrella category or conceptual family","canonical":"Dominance"},
  {"term":"Controlling the environment","disposition":"Noncanonical Taxonomy Term","taxonomy":"Manifestation of a pattern","canonical":"Schedule Domination"},
  {"term":"Controlling through caretaking","disposition":"Merged into Canonical Pattern","taxonomy":"Manifestation of a pattern","canonical":"Soliciting Dependence"},
  {"term":"Controlling through information","disposition":"Alias","taxonomy":"Alias or synonym","canonical":"Information Control"},
  {"term":"Controlling through withdrawal","disposition":"Merged into Canonical Pattern","taxonomy":"Manifestation of a pattern","canonical":"Punitive Withdrawal"},
  {"term":"Counterattack","disposition":"Noncanonical Taxonomy Term","taxonomy":"Relational behavior","canonical":"Retaliation"},
  {"term":"Credential accumulation","disposition":"Noncanonical Taxonomy Term","taxonomy":"Manifestation of a pattern","canonical":"Intelligence-Bound Worth"},
  {"term":"Credentialism","disposition":"Noncanonical Taxonomy Term","taxonomy":"Manifestation of a pattern","canonical":"Intelligence-Bound Worth"},
  {"term":"Crisis Creation","disposition":"Noncanonical Taxonomy Term","taxonomy":"Relational behavior","canonical":""},
  {"term":"Crisis creation through overextension","disposition":"Merged into Canonical Pattern","taxonomy":"Manifestation of a pattern","canonical":"Overfunctioning"},
  {"term":"Criticism","disposition":"Noncanonical Taxonomy Term","taxonomy":"Relational behavior","canonical":"Devaluation"},
  {"term":"Cross-Examination","disposition":"Alias","taxonomy":"Alias or synonym","canonical":"Interrogative Control"},
  {"term":"Cynicism","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Cynicism"},
  {"term":"DARVO","disposition":"Noncanonical Taxonomy Term","taxonomy":"Safety-framework term","canonical":""},
  {"term":"Decision Delegation","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Decision Delegation"},
  {"term":"Decision paralysis","disposition":"Noncanonical Taxonomy Term","taxonomy":"Cognitive state or process","canonical":"Certainty Seeking"},
  {"term":"Defensive expertise","disposition":"Duplicate","taxonomy":"Alias or synonym","canonical":"Defensive Expertise"},
  {"term":"Defensive Expertise","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Defensive Expertise"},
  {"term":"Defensiveness","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Defensiveness"},
  {"term":"Deflection","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Deflection"},
  {"term":"Demand Avoidance","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Demand Avoidance"},
  {"term":"Demanding certainty","disposition":"Merged into Canonical Pattern","taxonomy":"Manifestation of a pattern","canonical":"Certainty Seeking"},
  {"term":"Denial","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Denial"},
  {"term":"Dependency","disposition":"Noncanonical Taxonomy Term","taxonomy":"Relational dynamic or loop","canonical":"Underfunctioning"},
  {"term":"Despair as certainty","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Despair as Certainty"},
  {"term":"Devaluation","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Devaluation"},
  {"term":"Devaluation after disappointment","disposition":"Merged into Canonical Pattern","taxonomy":"Manifestation of a pattern","canonical":"Devaluation"},
  {"term":"Difficulty delegating","disposition":"Noncanonical Taxonomy Term","taxonomy":"Manifestation of a pattern","canonical":"Overfunctioning"},
  {"term":"Dismissiveness","disposition":"Noncanonical Taxonomy Term","taxonomy":"Relational behavior","canonical":"Devaluation"},
  {"term":"Displacement","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Displacement"},
  {"term":"Dissociation","disposition":"Noncanonical Taxonomy Term","taxonomy":"Defense mechanism or clinical concept","canonical":""},
  {"term":"Dissociative distancing","disposition":"Noncanonical Taxonomy Term","taxonomy":"Somatic or nervous-system state","canonical":""},
  {"term":"Distraction","disposition":"Noncanonical Taxonomy Term","taxonomy":"Coping strategy","canonical":""},
  {"term":"Dominance","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Dominance"},
  {"term":"Emotional Baiting","disposition":"Noncanonical Taxonomy Term","taxonomy":"Relational behavior","canonical":""},
  {"term":"Emotional Blackmail","disposition":"Noncanonical Taxonomy Term","taxonomy":"Safety-framework term","canonical":""},
  {"term":"Emotional chasing","disposition":"Noncanonical Taxonomy Term","taxonomy":"Manifestation of a pattern","canonical":"Clinging"},
  {"term":"Emotional Contagion","disposition":"Noncanonical Taxonomy Term","taxonomy":"Emotional state","canonical":""},
  {"term":"Emotional distancing","disposition":"Duplicate","taxonomy":"Alias or synonym","canonical":"Emotional Distancing"},
  {"term":"Emotional Distancing","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Emotional Distancing"},
  {"term":"Emotional Dumping","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Emotional Dumping"},
  {"term":"Emotional Flooding","disposition":"Noncanonical Taxonomy Term","taxonomy":"Somatic or nervous-system state","canonical":""},
  {"term":"Emotional Inhibition","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Emotional Inhibition"},
  {"term":"Emotional Neglect","disposition":"Noncanonical Taxonomy Term","taxonomy":"Safety-framework term","canonical":""},
  {"term":"Emotional numbing","disposition":"Duplicate","taxonomy":"Alias or synonym","canonical":"Emotional Numbing"},
  {"term":"Emotional Numbing","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Emotional Numbing"},
  {"term":"Emotional overresponsibility","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Emotional Overresponsibility"},
  {"term":"Emotional postponement","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Emotional Postponement"},
  {"term":"Emotional Reasoning","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Emotional Reasoning"},
  {"term":"Emotional sleight of hand","disposition":"Alias","taxonomy":"Alias or synonym","canonical":"Misdirection"},
  {"term":"Emotional Substitution","disposition":"Noncanonical Taxonomy Term","taxonomy":"Defense mechanism or clinical concept","canonical":""},
  {"term":"Emotional Withholding","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Emotional Withholding"},
  {"term":"Empathy Bypass","disposition":"Noncanonical Taxonomy Term","taxonomy":"Relational behavior","canonical":"Minimizing"},
  {"term":"Enabling","disposition":"Noncanonical Taxonomy Term","taxonomy":"Relational dynamic or loop","canonical":""},
  {"term":"Endless preparation","disposition":"Duplicate","taxonomy":"Alias or synonym","canonical":"Endless Preparation"},
  {"term":"Endless Preparation","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Endless Preparation"},
  {"term":"Endless revision","disposition":"Noncanonical Taxonomy Term","taxonomy":"Manifestation of a pattern","canonical":"Perfectionism"},
  {"term":"Entertainment saturation","disposition":"Noncanonical Taxonomy Term","taxonomy":"Coping strategy","canonical":""},
  {"term":"Entitlement","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Entitlement"},
  {"term":"Envy","disposition":"Noncanonical Taxonomy Term","taxonomy":"Emotional state","canonical":""},
  {"term":"Escape at the point of intimacy","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Escape at the Point of Intimacy"},
  {"term":"Escapism","disposition":"Noncanonical Taxonomy Term","taxonomy":"Umbrella category or conceptual family","canonical":"Fantasy Refuge"},
  {"term":"Escapist movement","disposition":"Noncanonical Taxonomy Term","taxonomy":"Manifestation of a pattern","canonical":""},
  {"term":"Exceptionalism","disposition":"Noncanonical Taxonomy Term","taxonomy":"Cognitive state or process","canonical":"Grandiosity"},
  {"term":"Excessive Apologizing","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Excessive Apologizing"},
  {"term":"Excessive Self-Monitoring","disposition":"Noncanonical Taxonomy Term","taxonomy":"Manifestation of a pattern","canonical":"Hypervigilance"},
  {"term":"Expert identity fixation","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Expert Identity Fixation"},
  {"term":"Explaining instead of apologizing","disposition":"Noncanonical Taxonomy Term","taxonomy":"Relational behavior","canonical":"Defensiveness"},
  {"term":"Exposure of others without self-exposure","disposition":"Alias","taxonomy":"Alias or synonym","canonical":"Asymmetric Exposure"},
  {"term":"Externalization","disposition":"Noncanonical Taxonomy Term","taxonomy":"Defense mechanism or clinical concept","canonical":"Blame Shifting"},
  {"term":"Externalized guidance","disposition":"Alias","taxonomy":"Alias or synonym","canonical":"Decision Delegation"},
  {"term":"Failure to launch","disposition":"Duplicate","taxonomy":"Alias or synonym","canonical":""},
  {"term":"Failure to Launch","disposition":"Noncanonical Taxonomy Term","taxonomy":"Outcome / cost / consequence","canonical":""},
  {"term":"Faith as avoidance","disposition":"Alias","taxonomy":"Alias or synonym","canonical":"Spiritual Bypassing"},
  {"term":"False agreement","disposition":"Noncanonical Taxonomy Term","taxonomy":"Relational behavior","canonical":"Avoidant Compliance"},
  {"term":"False Equivalence","disposition":"Noncanonical Taxonomy Term","taxonomy":"Cognitive state or process","canonical":""},
  {"term":"False humility","disposition":"Noncanonical Taxonomy Term","taxonomy":"Manifestation of a pattern","canonical":"Self-Deprecation"},
  {"term":"Fantasy bonding","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Fantasy Bonding"},
  {"term":"Fantasy escape","disposition":"Alias","taxonomy":"Alias or synonym","canonical":"Fantasy Refuge"},
  {"term":"Fantasy Refuge","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Fantasy Refuge"},
  {"term":"Fault finding","disposition":"Noncanonical Taxonomy Term","taxonomy":"Relational behavior","canonical":"Devaluation"},
  {"term":"Fear of Success","disposition":"Noncanonical Taxonomy Term","taxonomy":"Core wound or learned expectation","canonical":"Self-Sabotage"},
  {"term":"Flirtation without availability","disposition":"Noncanonical Taxonomy Term","taxonomy":"Relational behavior","canonical":"Strategic Ambiguity"},
  {"term":"Food as emotional regulation","disposition":"Noncanonical Taxonomy Term","taxonomy":"Coping strategy","canonical":""},
  {"term":"Forced Forgiveness","disposition":"Noncanonical Taxonomy Term","taxonomy":"Safety-framework term","canonical":"Spiritual Bypassing"},
  {"term":"Fusion","disposition":"Alias","taxonomy":"Alias or synonym","canonical":"Identity Fusion"},
  {"term":"Future Faking","disposition":"Noncanonical Taxonomy Term","taxonomy":"Safety-framework term","canonical":"Promise Inflation"},
  {"term":"Gaslighting","disposition":"Noncanonical Taxonomy Term","taxonomy":"Safety-framework term","canonical":""},
  {"term":"Gatekeeping","disposition":"Noncanonical Taxonomy Term","taxonomy":"Relational behavior","canonical":"Information Control"},
  {"term":"Ghosting","disposition":"Noncanonical Taxonomy Term","taxonomy":"Relational behavior","canonical":"Emotional Distancing"},
  {"term":"Gossip","disposition":"Noncanonical Taxonomy Term","taxonomy":"Relational behavior","canonical":""},
  {"term":"Grandiosity","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Grandiosity"},
  {"term":"Grudge holding","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Grudge Holding"},
  {"term":"Guilt Induction","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Guilt Induction"},
  {"term":"Guilt-based helping","disposition":"Noncanonical Taxonomy Term","taxonomy":"Manifestation of a pattern","canonical":"Guilt Induction"},
  {"term":"Help refusal","disposition":"Alias","taxonomy":"Alias or synonym","canonical":"Help-Rejection"},
  {"term":"Help-Rejection","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Help-Rejection"},
  {"term":"Helplessness Performance","disposition":"Noncanonical Taxonomy Term","taxonomy":"Manifestation of a pattern","canonical":"Underfunctioning"},
  {"term":"Hero identity fixation","disposition":"Alias","taxonomy":"Alias or synonym","canonical":"Savior Identity"},
  {"term":"Hostility toward criticism","disposition":"Duplicate","taxonomy":"Alias or synonym","canonical":"Hostility Toward Criticism"},
  {"term":"Hostility Toward Criticism","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Hostility Toward Criticism"},
  {"term":"Humor as deflection","disposition":"Alias","taxonomy":"Alias or synonym","canonical":"Humor Deflection"},
  {"term":"Humor Deflection","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Humor Deflection"},
  {"term":"Hyper-independence","disposition":"Duplicate","taxonomy":"Alias or synonym","canonical":"Hyper-Independence"},
  {"term":"Hyper-Independence","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Hyper-Independence"},
  {"term":"Hyper-Rationality","disposition":"Noncanonical Taxonomy Term","taxonomy":"Defense mechanism or clinical concept","canonical":"Moral Reasoning as Avoidance"},
  {"term":"Hyper-Responsibility","disposition":"Alias","taxonomy":"Alias or synonym","canonical":"Responsibility Inflation"},
  {"term":"Hypercriticism","disposition":"Noncanonical Taxonomy Term","taxonomy":"Relational behavior","canonical":"Internalized Critic"},
  {"term":"Hypervigilance","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Hypervigilance"},
  {"term":"Idealistic denial","disposition":"Merged into Canonical Pattern","taxonomy":"Manifestation of a pattern","canonical":"Denial"},
  {"term":"Idealization","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Idealization"},
  {"term":"Identity Diffusion","disposition":"Noncanonical Taxonomy Term","taxonomy":"Defense mechanism or clinical concept","canonical":""},
  {"term":"Identity foreclosure","disposition":"Noncanonical Taxonomy Term","taxonomy":"Cognitive state or process","canonical":"Identity Fusion"},
  {"term":"Identity Fusion","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Identity Fusion"},
  {"term":"Identity fusion with role","disposition":"Merged into Canonical Pattern","taxonomy":"Manifestation of a pattern","canonical":"Role Entrapment"},
  {"term":"Ideological rebellion","disposition":"Noncanonical Taxonomy Term","taxonomy":"Manifestation of a pattern","canonical":"Contrarianism"},
  {"term":"Image management","disposition":"Duplicate","taxonomy":"Alias or synonym","canonical":"Image Management"},
  {"term":"Image Management","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Image Management"},
  {"term":"Impostor concealment","disposition":"Merged into Canonical Pattern","taxonomy":"Manifestation of a pattern","canonical":"Impostorism"},
  {"term":"Impostorism","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Impostorism"},
  {"term":"Inability to rest","disposition":"Noncanonical Taxonomy Term","taxonomy":"Outcome / cost / consequence","canonical":"Productivity-Bound Worth"},
  {"term":"Indecision","disposition":"Noncanonical Taxonomy Term","taxonomy":"Cognitive state or process","canonical":"Certainty Seeking"},
  {"term":"Indispensability","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Indispensability"},
  {"term":"Information hoarding","disposition":"Merged into Canonical Pattern","taxonomy":"Manifestation of a pattern","canonical":"Information Control"},
  {"term":"Intellectualizing","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Intellectualizing"},
  {"term":"Intelligence-bound worth","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Intelligence-Bound Worth"},
  {"term":"Intermittent Reinforcement","disposition":"Noncanonical Taxonomy Term","taxonomy":"Relational dynamic or loop","canonical":""},
  {"term":"Internalized Critic","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Internalized Critic"},
  {"term":"Interrogative Control","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Interrogative Control"},
  {"term":"Intimidation","disposition":"Noncanonical Taxonomy Term","taxonomy":"Safety-framework term","canonical":""},
  {"term":"Irony dependence","disposition":"Noncanonical Taxonomy Term","taxonomy":"Manifestation of a pattern","canonical":"Humor Deflection"},
  {"term":"Isolation","disposition":"Noncanonical Taxonomy Term","taxonomy":"Relational behavior","canonical":"Self-Isolation"},
  {"term":"Jealous surveillance","disposition":"Noncanonical Taxonomy Term","taxonomy":"Safety-framework term","canonical":"Possessiveness"},
  {"term":"Jealousy","disposition":"Noncanonical Taxonomy Term","taxonomy":"Emotional state","canonical":""},
  {"term":"Keeping Score","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Keeping Score"},
  {"term":"Learned Helplessness","disposition":"Noncanonical Taxonomy Term","taxonomy":"Defense mechanism or clinical concept","canonical":""},
  {"term":"Loyalty Policing","disposition":"Noncanonical Taxonomy Term","taxonomy":"Safety-framework term","canonical":""},
  {"term":"Loyalty Tests","disposition":"Merged into Canonical Pattern","taxonomy":"Manifestation of a pattern","canonical":"Testing the Bond"},
  {"term":"Magical certainty","disposition":"Noncanonical Taxonomy Term","taxonomy":"Cognitive state or process","canonical":""},
  {"term":"Magical Thinking","disposition":"Noncanonical Taxonomy Term","taxonomy":"Defense mechanism or clinical concept","canonical":""},
  {"term":"Manufactured Urgency / Emergency-Making","disposition":"Noncanonical Taxonomy Term","taxonomy":"Relational behavior","canonical":""},
  {"term":"Martyrdom","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Martyrdom"},
  {"term":"Masking","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Masking"},
  {"term":"Material or Possession Hoarding","disposition":"Noncanonical Taxonomy Term","taxonomy":"Symptom or diagnostic indicator","canonical":""},
  {"term":"Meaning collapse","disposition":"Noncanonical Taxonomy Term","taxonomy":"Emotional state","canonical":""},
  {"term":"Meaning inflation","disposition":"Duplicate","taxonomy":"Alias or synonym","canonical":"Meaning Inflation"},
  {"term":"Meaning Inflation","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Meaning Inflation"},
  {"term":"Micromanaging","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Micromanaging"},
  {"term":"Mind reading","disposition":"Duplicate","taxonomy":"Alias or synonym","canonical":"Mind Reading"},
  {"term":"Mind Reading","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Mind Reading"},
  {"term":"Minimizing","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Minimizing"},
  {"term":"Misdirection","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Misdirection"},
  {"term":"Moral Licensing","disposition":"Noncanonical Taxonomy Term","taxonomy":"Cognitive state or process","canonical":""},
  {"term":"Moral reasoning as avoidance","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Moral Reasoning as Avoidance"},
  {"term":"Moral superiority","disposition":"Duplicate","taxonomy":"Alias or synonym","canonical":"Moral Superiority"},
  {"term":"Moral Superiority","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Moral Superiority"},
  {"term":"Moral worth performance","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Moral Worth Performance"},
  {"term":"Moving the Goalposts","disposition":"Noncanonical Taxonomy Term","taxonomy":"Relational behavior","canonical":"Semantic Control"},
  {"term":"Mystery cultivation","disposition":"Noncanonical Taxonomy Term","taxonomy":"Manifestation of a pattern","canonical":"Strategic Ambiguity"},
  {"term":"Naïve trust","disposition":"Noncanonical Taxonomy Term","taxonomy":"Trait or temperament","canonical":""},
  {"term":"Name-dropping or borrowed prestige","disposition":"Noncanonical Taxonomy Term","taxonomy":"Manifestation of a pattern","canonical":"Status Guarding"},
  {"term":"Narrative Fusion","disposition":"Noncanonical Taxonomy Term","taxonomy":"Cognitive state or process","canonical":"Identity Fusion"},
  {"term":"Narrative overcontrol","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Narrative Overcontrol"},
  {"term":"Need suppression","disposition":"Duplicate","taxonomy":"Alias or synonym","canonical":"Self-Erasure"},
  {"term":"Need Suppression","disposition":"Merged into Canonical Pattern","taxonomy":"Manifestation of a pattern","canonical":"Self-Erasure"},
  {"term":"Novelty chasing","disposition":"Noncanonical Taxonomy Term","taxonomy":"Manifestation of a pattern","canonical":""},
  {"term":"Novelty Seeking","disposition":"Noncanonical Taxonomy Term","taxonomy":"Trait or temperament","canonical":""},
  {"term":"Novelty substitution","disposition":"Noncanonical Taxonomy Term","taxonomy":"Coping strategy","canonical":""},
  {"term":"Obligation Leverage","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Obligation Leverage"},
  {"term":"One-Upmanship","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"One-Upmanship"},
  {"term":"Outcome attachment","disposition":"Noncanonical Taxonomy Term","taxonomy":"Cognitive state or process","canonical":""},
  {"term":"Outsider identity fixation","disposition":"Noncanonical Taxonomy Term","taxonomy":"Archetypal role or expression","canonical":"Identity Fusion"},
  {"term":"Overaccommodation","disposition":"Noncanonical Taxonomy Term","taxonomy":"Manifestation of a pattern","canonical":"People-Pleasing"},
  {"term":"Overcommitment","disposition":"Noncanonical Taxonomy Term","taxonomy":"Manifestation of a pattern","canonical":"Overfunctioning"},
  {"term":"Overcomplication","disposition":"Noncanonical Taxonomy Term","taxonomy":"Cognitive state or process","canonical":""},
  {"term":"Overexplaining","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Overexplaining"},
  {"term":"Overfunctioning","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Overfunctioning"},
  {"term":"Overinterpretation","disposition":"Noncanonical Taxonomy Term","taxonomy":"Cognitive state or process","canonical":"Mind Reading"},
  {"term":"Overplanning","disposition":"Noncanonical Taxonomy Term","taxonomy":"Manifestation of a pattern","canonical":"Endless Preparation"},
  {"term":"Overpromising","disposition":"Alias","taxonomy":"Alias or synonym","canonical":"Promise Inflation"},
  {"term":"Oversharing","disposition":"Alias","taxonomy":"Alias or synonym","canonical":"Confessional Overexposure"},
  {"term":"Overwork","disposition":"Noncanonical Taxonomy Term","taxonomy":"Manifestation of a pattern","canonical":"Productivity-Bound Worth"},
  {"term":"Pain Competition","disposition":"Noncanonical Taxonomy Term","taxonomy":"Relational behavior","canonical":"One-Upmanship"},
  {"term":"Passive Aggression","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Passive Aggression"},
  {"term":"Procrastination through protection","disposition":"Noncanonical Taxonomy Term","taxonomy":"Protective purpose or emotional function","canonical":"Endless Preparation"},
  {"term":"Productivity-bound worth","disposition":"Duplicate","taxonomy":"Alias or synonym","canonical":"Productivity-Bound Worth"},
  {"term":"Productivity-Bound Worth","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Productivity-Bound Worth"},
  {"term":"Projection","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Projection"},
  {"term":"Promise Inflation","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Promise Inflation"},
  {"term":"Proving worth through usefulness","disposition":"Merged into Canonical Pattern","taxonomy":"Manifestation of a pattern","canonical":"Productivity-Bound Worth"},
  {"term":"Provocation","disposition":"Noncanonical Taxonomy Term","taxonomy":"Relational behavior","canonical":""},
  {"term":"Punitive silence","disposition":"Duplicate","taxonomy":"Alias or synonym","canonical":""},
  {"term":"Punitive Silence","disposition":"Alias","taxonomy":"Alias or synonym","canonical":""},
  {"term":"Punitive Withdrawal","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":""},
  {"term":"Purity identity","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Purity Identity"},
  {"term":"Purity through withdrawal","disposition":"Noncanonical Taxonomy Term","taxonomy":"Manifestation of a pattern","canonical":"Purity Identity"},
  {"term":"Rapid project proliferation","disposition":"Duplicate","taxonomy":"Alias or synonym","canonical":""},
  {"term":"Rapid Project Proliferation","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":""},
  {"term":"Rationalization","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Rationalization"},
  {"term":"Reaction Formation","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Reaction Formation"},
  {"term":"Reassurance loops","disposition":"Merged into Canonical Pattern","taxonomy":"Relational dynamic or loop","canonical":"Reassurance Seeking"},
  {"term":"Reassurance Seeking","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Reassurance Seeking"},
  {"term":"Rebellion as Identity","disposition":"Noncanonical Taxonomy Term","taxonomy":"Archetypal role or expression","canonical":"Contrarianism"},
  {"term":"Reciprocity Anxiety","disposition":"Noncanonical Taxonomy Term","taxonomy":"Emotional state","canonical":"Keeping Score"},
  {"term":"Rehearsing conversations","disposition":"Alias","taxonomy":"Alias or synonym","canonical":"Compulsive Rehearsal"},
  {"term":"Rejection Preemption","disposition":"Alias","taxonomy":"Alias or synonym","canonical":"Preemptive Self-Rejection"},
  {"term":"Rejection Sensitivity","disposition":"Noncanonical Taxonomy Term","taxonomy":"Trait or temperament","canonical":""},
  {"term":"Relationship hopping","disposition":"Noncanonical Taxonomy Term","taxonomy":"Manifestation of a pattern","canonical":""},
  {"term":"Relationship overinvestment","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Relationship Overinvestment"},
  {"term":"Relationship-bound worth","disposition":"Duplicate","taxonomy":"Alias or synonym","canonical":"Relationship-Bound Worth"},
  {"term":"Relationship-Bound Worth","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Relationship-Bound Worth"},
  {"term":"Rescuing","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Rescuing"},
  {"term":"Resentment","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Resentment"},
  {"term":"Resource Guarding","disposition":"Noncanonical Taxonomy Term","taxonomy":"Relational behavior","canonical":""},
  {"term":"Responsibility inflation","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Responsibility Inflation"},
  {"term":"Restlessness","disposition":"Noncanonical Taxonomy Term","taxonomy":"Somatic or nervous-system state","canonical":""},
  {"term":"Retaliation","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Retaliation"},
  {"term":"Retrospective prosecution","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Retrospective Prosecution"},
  {"term":"Revelation addiction","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Revelation Addiction"},
  {"term":"Revenge fantasy","disposition":"Noncanonical Taxonomy Term","taxonomy":"Cognitive state or process","canonical":"Retaliation"},
  {"term":"Rigidity","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Rigidity"},
  {"term":"Risk Avoidance","disposition":"Noncanonical Taxonomy Term","taxonomy":"Coping strategy","canonical":""},
  {"term":"Role Entrapment","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Role Entrapment"},
  {"term":"Rule breaking for self-definition","disposition":"Noncanonical Taxonomy Term","taxonomy":"Manifestation of a pattern","canonical":""},
  {"term":"Rule dependence","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Rule Dependence"},
  {"term":"Rumination","disposition":"Noncanonical Taxonomy Term","taxonomy":"Cognitive state or process","canonical":""},
  {"term":"Sabotaging dependence","disposition":"Unresolved","taxonomy":"Relational behavior","canonical":""},
  {"term":"Sarcasm as armor","disposition":"Duplicate","taxonomy":"Alias or synonym","canonical":"Sarcasm as Armor"},
  {"term":"Sarcasm as Armor","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Sarcasm as Armor"},
  {"term":"Savior Identity","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Savior Identity"},
  {"term":"Scapegoating","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Scapegoating"},
  {"term":"Scarcity Hoarding","disposition":"Noncanonical Taxonomy Term","taxonomy":"Coping strategy","canonical":""},
  {"term":"Schedule domination","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Schedule Domination"},
  {"term":"Score-Settling","disposition":"Merged into Canonical Pattern","taxonomy":"Manifestation of a pattern","canonical":"Retaliation"},
  {"term":"Scorecard Reciprocity","disposition":"Alias","taxonomy":"Alias or synonym","canonical":"Keeping Score"},
  {"term":"Secret keeping for identity protection","disposition":"Noncanonical Taxonomy Term","taxonomy":"Protective purpose or emotional function","canonical":""},
  {"term":"Secret-Keeping","disposition":"Noncanonical Taxonomy Term","taxonomy":"Relational behavior","canonical":""},
  {"term":"Seduction","disposition":"Noncanonical Taxonomy Term","taxonomy":"Relational behavior","canonical":""},
  {"term":"Seduction as validation","disposition":"Noncanonical Taxonomy Term","taxonomy":"Manifestation of a pattern","canonical":""},
  {"term":"Selective Accountability","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Selective Accountability"},
  {"term":"Selective Disclosure","disposition":"Noncanonical Taxonomy Term","taxonomy":"Relational behavior","canonical":""},
  {"term":"Selective Vulnerability","disposition":"Noncanonical Taxonomy Term","taxonomy":"Healthy behavior or contextual adaptation","canonical":""},
  {"term":"Self-Condemnation","disposition":"Noncanonical Taxonomy Term","taxonomy":"Cognitive state or process","canonical":""},
  {"term":"Self-deprecation","disposition":"Duplicate","taxonomy":"Alias or synonym","canonical":"Self-Deprecation"},
  {"term":"Self-Deprecation","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Self-Deprecation"},
  {"term":"Self-erasure","disposition":"Duplicate","taxonomy":"Alias or synonym","canonical":"Self-Erasure"},
  {"term":"Self-Erasure","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Self-Erasure"},
  {"term":"Self-Handicapping","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Self-Handicapping"},
  {"term":"Self-Isolation","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Self-Isolation"},
  {"term":"Self-neglect through service","disposition":"Noncanonical Taxonomy Term","taxonomy":"Manifestation of a pattern","canonical":"Martyrdom"},
  {"term":"Self-Sabotage","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Self-Sabotage"},
  {"term":"Self-Silencing","disposition":"Merged into Canonical Pattern","taxonomy":"Manifestation of a pattern","canonical":"Emotional Inhibition"},
  {"term":"Semantic control","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Semantic Control"},
  {"term":"Shame Spiraling","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Shame Spiraling"},
  {"term":"Shapeshifting","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Shapeshifting"},
  {"term":"Shutdown","disposition":"Noncanonical Taxonomy Term","taxonomy":"Somatic or nervous-system state","canonical":""},
  {"term":"Silence as Protest","disposition":"Noncanonical Taxonomy Term","taxonomy":"Relational behavior","canonical":""},
  {"term":"Silent Treatment","disposition":"Noncanonical Taxonomy Term","taxonomy":"Safety-framework term","canonical":"Punitive Withdrawal"},
  {"term":"Sleep as escape","disposition":"Noncanonical Taxonomy Term","taxonomy":"Coping strategy","canonical":""},
  {"term":"Soliciting dependence","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Soliciting Dependence"},
  {"term":"Somatic Alarm Fixation","disposition":"Noncanonical Taxonomy Term","taxonomy":"Symptom or diagnostic indicator","canonical":"Hypervigilance"},
  {"term":"Spiritual bypassing","disposition":"Duplicate","taxonomy":"Alias or synonym","canonical":"Spiritual Bypassing"},
  {"term":"Spiritual Bypassing","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Spiritual Bypassing"},
  {"term":"Splitting","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Splitting"},
  {"term":"Status Guarding","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Status Guarding"},
  {"term":"Status seeking","disposition":"Noncanonical Taxonomy Term","taxonomy":"Manifestation of a pattern","canonical":"Status Guarding"},
  {"term":"Stonewalling","disposition":"Noncanonical Taxonomy Term","taxonomy":"Relational behavior","canonical":"Punitive Withdrawal"},
  {"term":"Strategic Ambiguity","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Strategic Ambiguity"},
  {"term":"Substance-based avoidance","disposition":"Noncanonical Taxonomy Term","taxonomy":"Coping strategy","canonical":""},
  {"term":"Suffering as meaning","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Suffering as Meaning"},
  {"term":"Suspicion","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Suspicion"},
  {"term":"Testing the bond","disposition":"Duplicate","taxonomy":"Alias or synonym","canonical":"Testing the Bond"},
  {"term":"Testing the Bond","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Testing the Bond"},
  {"term":"Threat Generalization","disposition":"Noncanonical Taxonomy Term","taxonomy":"Cognitive state or process","canonical":"Hypervigilance"},
  {"term":"Toxic positivity","disposition":"Duplicate","taxonomy":"Alias or synonym","canonical":"Positivity Enforcement"},
  {"term":"Toxic Positivity","disposition":"Alias","taxonomy":"Alias or synonym","canonical":"Positivity Enforcement"},
  {"term":"Triangulation","disposition":"Noncanonical Taxonomy Term","taxonomy":"Relational dynamic or loop","canonical":""},
  {"term":"Trigger Stacking","disposition":"Noncanonical Taxonomy Term","taxonomy":"Somatic or nervous-system state","canonical":""},
  {"term":"Truth telling as domination","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Truth Telling as Domination"},
  {"term":"Underfunctioning","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Underfunctioning"},
  {"term":"Underpromising as concealment","disposition":"Noncanonical Taxonomy Term","taxonomy":"Manifestation of a pattern","canonical":"Strategic Ambiguity"},
  {"term":"Undoing","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Undoing"},
  {"term":"Unsolicited Fixing","disposition":"Merged into Canonical Pattern","taxonomy":"Relational behavior","canonical":"Advice-Giving as Avoidance"},
  {"term":"Urgency Addiction","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Urgency Addiction"},
  {"term":"Venting Loop","disposition":"Noncanonical Taxonomy Term","taxonomy":"Relational dynamic or loop","canonical":"Emotional Dumping"},
  {"term":"Victim identity fixation","disposition":"Duplicate","taxonomy":"Alias or synonym","canonical":"Victim Identity Fixation"},
  {"term":"Victim Identity Fixation","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Victim Identity Fixation"},
  {"term":"Victim-Offender Reversal","disposition":"Noncanonical Taxonomy Term","taxonomy":"Safety-framework term","canonical":""},
  {"term":"Virtue signaling","disposition":"Noncanonical Taxonomy Term","taxonomy":"Manifestation of a pattern","canonical":"Moral Worth Performance"},
  {"term":"Vulnerability Avoidance","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Vulnerability Avoidance"},
  {"term":"Weaponized Incompetence","disposition":"Noncanonical Taxonomy Term","taxonomy":"Safety-framework term","canonical":"Underfunctioning"},
  {"term":"Whataboutism","disposition":"Noncanonical Taxonomy Term","taxonomy":"Cognitive state or process","canonical":"Deflection"},
  {"term":"Withdrawing before being left","disposition":"Duplicate","taxonomy":"Alias or synonym","canonical":"Withdrawing Before Being Left"},
  {"term":"Withdrawing Before Being Left","disposition":"Canonical Protective Pattern","taxonomy":"Canonical Protective Pattern","canonical":"Withdrawing Before Being Left"},
  {"term":"Withholding Affection","disposition":"Noncanonical Taxonomy Term","taxonomy":"Safety-framework term","canonical":"Conditional Warmth"}
];

// Count summary — 360 unique terms total:
//   Noncanonical Taxonomy Term: 150
//   Canonical Protective Pattern: 137
//   Duplicate: 30
//   Alias: 26
//   Merged into Canonical Pattern: 16
//   Unresolved: 1
//   with canonical resolved: 288
